#!/bin/sh

set -eu
basedir="$(dirname "$0")"

export PRISTINE_TAR_VERSION="$(cd "$basename" && git describe --tags | sed -e 's#debian/##')"
export PATH="$basedir:$PATH"
export PERL5LIB="$basedir"

exec "$@"
